version: '3.8'
services:  
  redis:    
    container_name: movies-db-redis
    image: redis:latest
    restart: always
    ports:      
      - "6379:6379"    
    volumes:       
      - redis-data:/data
volumes:    
  redis-data: